Add metacontact to the CCA manager
AY2324S2-CS2103T-W11-2/tp pull request #107
Opened 2024-04-02 12:19 UTC by alphajae11

Add metacontact to the CCA manager

2024-04-03 08:25 UTC, JuliaPoo requested changes
I did not look through all of the code yet or ran the branch yet, but in general, be more thorough in understand where needs to be modified.

The reason why this feature seems to have so many code changes is because you did not make metadata an optional. If you did your changes dont have to be so invasive.

2024-04-03 08:25 UTC, JuliaPoo commented on src/main/java/seedu/address/logic/commands/AddCommand.java
>              + PREFIX_ROLE + "owesMoney"
Formatting error: `"owesMoney"` should be `"owesMoney "`

2024-04-03 08:25 UTC, JuliaPoo commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +            + PREFIX_METADATA + "I have food allegeries - Egg and Peanuts"
Formatting error: `"I have food allegeries - Egg and Peanuts"` should be `"I have food allegeries - Egg and Peanuts "`

2024-04-03 08:25 UTC, JuliaPoo commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +            + "[" + PREFIX_METADATA + "Meta-data]...\n"
Formatting error: 
```
+ "[" + PREFIX_CCA + "CCA]...\n"
+ "[" + PREFIX_METADATA + "Meta-data]...\n"
```

should be

```
+ "[" + PREFIX_CCA + "CCA] "
+ "[" + PREFIX_METADATA + "Meta-data]...\n"
```

2024-04-03 08:25 UTC, JuliaPoo commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +            setMetadata(toCopy.metadata);
Github doesnt allow me to comment below but `isAnyFieldEdited` needs to be editted.

2024-04-03 08:29 UTC, JuliaPoo requested changes
Still have not looked through everything or ran ur code yet, but i found one more mistake

2024-04-03 08:29 UTC, JuliaPoo commented on src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
> +    "Metadata" : "I like to do leetcode everyday."
Shoud not be "Metadata", should be "metadata".

2024-04-03 15:56 UTC, JuliaPoo approved these changes

2024-04-03 17:30 UTC, merged

2024-04-04 13:13 UTC, chuahjiajie reviewed
Overall looks good, just have a few questions. Thanks!

2024-04-04 13:13 UTC, chuahjiajie commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +            + PREFIX_METADATA + "I have food allegeries - Egg and Peanuts "
Is this metadata relevant to our apps vision?

2024-04-04 13:13 UTC, chuahjiajie commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_METADATA = new Prefix("d/");
Why was "d/" chosen as the prefix?

2024-04-04 13:13 UTC, chuahjiajie commented on src/main/java/seedu/address/model/person/Metadata.java
> +    public static final String VALIDATION_REGEX = "[^/]+";
Smart use of regex

2024-04-04 13:13 UTC, chuahjiajie commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +                getRoleSet("family"), getCcaSet("NUS Cycling"), new Amount("0.0"),
Good work updating all the sample data

2024-04-04 13:13 UTC, chuahjiajie commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +    private final String metadata;
You sure only a string is enough, wouldn't it be better to make a JSONAdaptedMetaData?