Add Use Cases, Target user profile, value proposition, and user stories documentation
AY2324S2-CS2103T-W11-2/tp pull request #14
Opened 2024-03-02 16:31 UTC by alphajae11

Developer Guide has been edited to include more details about the project - CCA Manager.

Add Use Cases, Target user profile, value proposition, and user stories documentation of this project. All of the details are documented until version 1.2. The above information for the remaining features that will be made in later versions will be updated to the Developer Guide later.

2024-03-03 04:33 UTC, JuliaPoo requested changes
Yea looks good apart from that

2024-03-03 04:33 UTC, JuliaPoo commented on docs/DeveloperGuide.md
> +UC03 )Identify the EXCO members
`UC03 )` -> `UC03) `

2024-03-03 04:35 UTC, JuliaPoo approved these changes

2024-03-03 04:47 UTC, JuliaPoo commented
Actually if you don't mind I'll do some formatting to this branch?
In particular:
- Standardise (and inline-code) glossary terms
- Inline-code verbatim texts
- Use markdown's enumerations (instead of `2a)` etc)

2024-03-03 05:19 UTC, JuliaPoo commented
Fixes #10.

2024-03-04 06:05 UTC, merged

2024-03-04 06:06 UTC, alphajae11 commented
fixes #10 #9